name: Setup Node
description: Ensures NodeJS is on the correct version and installs dependencies
runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '18.16'
        cache: yarn
    - name: Install dependencies
      run:         
        yarn --immutable --prefer-offline
      shell: bash