version: '1.0'

x-common-variables:
  &common-variables
  MONGO_URI: &mongo-uri mongodb://root:root123@mongodb-primary:27017/dbName?authSource=admin

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
      MODE: API
    env_file: .env
    tty: true
  
  mongodb-primary:
    image: &mongodb-image bitnami/mongodb:4.0.27
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: &mongo-root-password root123
      MONGODB_REPLICA_SET_KEY: &mongo-replica-set-key replicasetkey123
      MONGODB_EXTRA_FLAGS: --bind_ip_all
    volumes:
      - mongodb_master_data:/bitnami/mongodb
  
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    depends_on:
      - mongodb-primary
    ports:
      - 8081:8081
    environment:
      <<: *common-variables
      # ME_CONFIG_MONGODB_URL: *mongo-uri
      ME_CONFIG_MONGODB_URL: mongodb://root:root123@mongodb-primary:27017/
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  
volumes:
  mongodb_master_data:
    driver: local