name: CI/CD Pipeline

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest    
    env:
      REDIS_URL: localhost
      REDIS_PORT: '6379'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        run: docker compose -f docker-compose.workflow-test.yml up -d --wait
      - name: Test the app
        run: docker exec -it backend-nestjs-template-app-1 yarn test
