name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest    
    env:
      REDIS_URL: localhost
      REDIS_PORT: '6379'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        run: docker compose -f docker-compose.workflow-test.yml up -d --wait
      - name: The image
        run: docker exec -it app yarn test
