name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
    env:
      REDIS_URL: localhost
      REDIS_PORT: '6379'
    steps:
        - 
          name: Checkout
          uses: actions/checkout@v4
        - 
          name: Build the Docker image
          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --progress=plain --no-cache --target test
